### ISSUE TITLE
support multi-realm

### ISSUE THREAD

**Issue by Helias** [azerothcore/acore-cms#124]
Feature that allows to the user to choose the realm when he is buying an item

**Comment by Yehonal** [comment]
This feature should be implemented using the Wordpress multi-site and/or multi-network feature

That feature allows you to setup multiple Wordpress website under the same domain, hence having separated shops, prices and configurations

It is the best way rather than implementing complex logic for each of our plugin

What do you think?

**Comment by Yehonal** [comment]
https://developer.wordpress.org/advanced-administration/multisite/

**Comment by Helias** [comment]
if it's simple and it allows to keep the same user account between the multiple Wordpress instances it's ok
we should use it and document how to setup it locally for development and usage

**Comment by Yehonal** [comment]
Yes it's easy and we used for AS when we had the 2 realms
